"""Session Token Column

Revision ID: 2fc21491034c
Revises: 012cc3eb4027
Create Date: 2020-06-15 13:38:47.533716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc21491034c'
down_revision = '012cc3eb4027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_token')
    # ### end Alembic commands ###
